export const products = [
    {
        "id": "1",
        "title": "Generic Metal Fish",
        "brand": "Dev Byte",
        "company": "TechGadget",
        "color": "Silver",
        "category": "Keyboard",        
        "image": "https://images.pexels.com/photos/21067/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "price": 623,
        "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7-Color RGB LED Back-lighting for smart functionality",             
      },
      {
        "id": "2",
        "title": "Slim Maple Gaming Laptop",
        "brand": "Dev Byte",
        "company": "TechGadget",
        "color": "Black",
        "category": "Laptop",
        "image": "https://images.pexels.com/photos/19012039/pexels-photo-19012039/free-photo-of-acer-predator-triton-300-se-gaming-laptop-connected-to-a-monitor.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",        
        "price": 699,
        "description": "The powerful Slim Maple Gaming Laptop from Dev Byte features a high-performance processor and a backlit keyboard for an immersive gaming experience.",        
      },
      {
        "id": "3",
        "title": "Dev Byte Professional PC",
        "brand": "Dev Byte",
        "company": "TechGadget",
        "color": "Gray",
        "category": "Laptop",
        "image": "https://images.pexels.com/photos/17784701/pexels-photo-17784701/free-photo-of-gaming-computer-laptop-and-keyboard-on-desk.jpeg",        
        "price": 799,
        "description": "The Dev Byte Professional Notebook offers top-notch performance with a sleek design, making it ideal for professionals on the go.",               
      },
      {
  "id": "4",
  "title": "Dev Byte Professional Notebook 01",
  "brand": "Dev Byte",
  "company": "TechGadget",
  "color": "Gray",
  "price": 799,
  "description": "The Dev Byte Professional Notebook offers top-notch performance with a sleek design, making it ideal for professionals on the go.",
  "image": "https://cdn.pixabay.com/photo/2017/11/27/21/31/computer-2982270_1280.jpg",
  "creationAt": "2024-01-03T12:30:45.000Z",
  "updatedAt": "2024-01-03T12:30:45.000Z",
  "category": "electronics"
  }
]